### ISSUE TITLE
One recording...different results... (propeller stops)

### ISSUE THREAD

**Issue by SoCalDude** [nguyenquyhy/Flight-Recorder#15]
Flight Recorder Version: **0.8.0.0**
Aircraft: **Cessna 172 Skyhawk (non-G1000)**

I recorded a landing. I replayed three different times, each being viewed from a different perspective. From inside the cockpit, the propeller would stop spinning while taxing on the runway (after the landing). From the drone camera in front of the airplane (looking at the front of it), the propeller would also stop (at about the same place on the runway). From the drone camera from the rear and side of the airplane (4 o'clock position), the propeller keeps spinning (as it should).

So, the same recording viewed at multiple angles produces different effects.

_Attached is the recording._..
[flight-recorder-prop-stops.zip](https://github.com/nguyenquyhy/Flight-Recorder/files/6008561/flight-recorder-prop-stops.zip)

**Comment by SoCalDude** [comment]
Here is a link to the video from which I recorded from the Flight Recorder playback...

[_https://youtu.be/WFMBG1oGy9Y_](https://youtu.be/WFMBG1oGy9Y)

**Comment by nguyenquyhy** [comment]
Yup I looked at the video. In the first 2 replay, the engine is not running. The prop is spinning because you are flying and have airspeed. I have no idea if that is realistic but that's how the sim works. This is one of the reason I said it is tricky to detect if the engine is running by looking at RPM. As I have noted, the tool doesn't start the engine for you, so if the engine is not running, the replay can look weird.

Also, you can also hear the constant switch sound inside the cockpit. Something is interfering with the replay, might not be related to the engine issue though. I would guess that you are using the Alpha yoke or Bravo throttle as those 2 send repeating commands to the sim which can interfere with a lot of stuff. One of the very annoying aspect of Honeycomb product.

I will look more into the flap issue. It can be a bug in the tool.

**Comment by nguyenquyhy** [comment]
Since the replay doesn't do mixture control, you can reproduce the first 2 videos easily by replaying while leaving mixture cut-off. You'll see props spinning due to the airspeed, and will stop spinning once you are on the ground and bleeded off almost all airspeed.

So basically the best course of action for the moment is to always start/stop recording/replaying when engine is running as I have noted in the description.

**Comment by SoCalDude** [comment]
Interesting.

I flew from 175 miles before this landing so the engine was definitely on. I did cut the throttle to idle as I glided over the threshold, with the mixture on rich. I started recording on my base approach.

By the way, I'm using the Saitek/Logitech yoke and throttle quadrant. 

Thank you for looking into this, though.

**Comment by nguyenquyhy** [comment]
No no I believe the flight itself is totally fine. However, when you ended the flight, you might cut the mixture to turn off the engine. 
So if you immediately start the replay, mixture stays cutoff and engine doesn't start.
