### ISSUE TITLE
Flight recorder crashes after replay if plane crashes

### ISSUE THREAD

**Issue by fayak** [nguyenquyhy/Flight-Recorder#6]
Hello !

First of all, thank you so much for your tool, it's really nice and covers nicely an important feature that was missing from MFS20: good job !

I noticed that if I crash my plane, and watch the replay, at the end of the replay when the plane crashes, Flight Recorder also crashes. Is it intended behavior ?

Also, there are some some "hiccups" whilst in flight, but I'm not sure that you can do something about it.

Best regards

**Comment by nguyenquyhy** [comment]
Thanks for letting me know about the crash. I'll fix it in the next version.

About the hiccups, I believe you are talking about a very short pause every few seconds. If so, I am trying to track it down too. I am not very sure if it due to some lag during recording or replaying or some mistake in interpolation calculation. I relatively hard to track down so I'm still working on that.

**Comment by nguyenquyhy** [comment]
The crash should be fixed in v0.10.
