### ISSUE TITLE
Exe not running

### ISSUE THREAD

**Issue by Rainbowtits** [nguyenquyhy/Flight-Recorder#78]
Hi!
The app has worked for me only twice and I have had no luck after that. I have tried running it in Admin mode. I have tried reinstalling. I have tried it with different versions of MSFS and even another disc. The app just doesnt start at all. Nothing happens.

This seems like an awsome addo, and I hate to miss out!

Best regards
Phil

**Comment by nguyenquyhy** [comment]
My best guess for this would be that the folder lost some files. Have you tried to redownload and unzip the folder again?

**Comment by parkingbrake** [comment]
Hello together,
I've the Same issues. I Start the Client but the recorder cant connect to the sim..

**Comment by Rainbowtits** [comment]
Hi! I did try redownloading many times but the issue seems to finally have sorted it self out.

At first it only worked when the .exe file was in its original folder (so this could be a workaround solution for others!). Now it seems to work as intended and I can start the exe shortcut from the desktop. 
Thank you!

**Comment by parkingbrake** [comment]
hello Nguyen,

 

sorry but i was today the first time again in my e-mail box ;-)

 

@ 1 thank you for your awnser ..

 

so i have  try to installed your software and even i´ve got the proplem ..

cannot simconnect ;-(

 

i bought then a flight recorder from sim marked and try thisone...

 

its unbeleavable but again the software can not running.

 

Same time i try the bought programme to install at my older pc ( working under win 7 ) .. that works.

 

So my faforit software woult like to be yours but it doesn´t work.

 

My system check looks like this.

 

my framenetwork in the list checket with 3.5 and 4 ?? 

the aktuell simconnect  is listet

my msfs runs on a omen hp gaming lap

so i really dont know what i can do.

 

please please please help me ;-)

 

and once more...

 

thank you for your time.

 

Hans

 
 

Gesendet: Dienstag, 11. Mai 2021 um 04:59 Uhr
Von: "Nguyễn Quý Hy" ***@***.***>
An: "nguyenquyhy/Flight-Recorder" ***@***.***>
Cc: "parkingbrake" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [nguyenquyhy/Flight-Recorder] Exe not running (#78)


 

Oh the exe need to be with other files in the package. Yah you can't move just the exe outside since it will fail to load all the necessary libraries.

**Comment by nguyenquyhy** [comment]
I think this is an issue with SimConnect installation in your PC. Are you able to ping me (Hy) in my Discord server? It's a bit hard to troubleshoot this way. https://discord.gg/azqQrWWEbV

**Comment by parkingbrake** [comment]
hello again i´ve got some pics

 

pherhaps you can fix my issue ... 

 

 

 
 

Gesendet: Dienstag, 11. Mai 2021 um 04:59 Uhr
Von: "Nguyễn Quý Hy" ***@***.***>
An: "nguyenquyhy/Flight-Recorder" ***@***.***>
Cc: "parkingbrake" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [nguyenquyhy/Flight-Recorder] Exe not running (#78)


 

Oh the exe need to be with other files in the package. Yah you can't move just the exe outside since it will fail to load all the necessary libraries.

**Comment by parkingbrake** [comment]
hi :-)

 

i pressed your link im already there i think... what should i do

 
 

Gesendet: Freitag, 14. Mai 2021 um 20:19 Uhr
Von: "Nguyễn Quý Hy" ***@***.***>
An: "nguyenquyhy/Flight-Recorder" ***@***.***>
Cc: "parkingbrake" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [nguyenquyhy/Flight-Recorder] Exe not running (#78)


 

I think this is an issue with SimConnect installation in your PC. Are you able to ping me (Hy) in my Discord server? It's a bit hard to troubleshoot this way. https://discord.gg/azqQrWWEbV

**Comment by parkingbrake** [comment]
Hello hy,
We told via ping At 14.5.21 about some Probleme and issues in accordance with my PC and your famos programm flight recorder....
I try a lot but nothing happend..also i bought a flight recorder and i can not beleave it.... this programm does not work too.
Cold it be that this is a Propaganda with my win 10 Version or with my msfs2020?? 
I have Box deluxe premium but thats really the biggest riddle ...i only want to Review my landings in lukla 😁 
Can you Help me once??
My Laptop omen HP gaming with win10 bought him in the Middle of April 21 pherhaps this Information Help you a Bit....
Thank you verry much and hope you have a idea...

Greatings from germany 

Hans

**Comment by nguyenquyhy** [comment]
Please try again with latest version. This should not happen anymore.
