### ISSUE TITLE
Playback very jittery on the Bell 47

### ISSUE THREAD

**Issue by mauben45** [nguyenquyhy/Flight-Recorder#81]
I am recording flights on the new Bell 47. Almost everything works great, but when I play back the recording, the cyclic moves wildly when in fact, it should barely move. Also, the instruments do not show the correct values. For instance the speed gauge does not even work.
You can see what I am talking about in this video. Is this problem only happening because this is a helicopter? Other than that, great program.
Thank you,
Maurice

 https://youtu.be/rH2poSmAxTE

**Comment by nguyenquyhy** [comment]
I might be wrong about this because I don't have the Bell 47, but from what I have observed and heard, the Bell 47 uses a custom control binding mechanism and custom flight model. This means they might constantly try to overwrite MSFS's built-in mechanism. 

So this is my guess on what happens: every frame, Flight Recorder sends a particular flight control position to the sim, then immediately after, Bell 47 custom software reads your stick position and try to overwrite the same value. This keeps repeating creating the flickering.

**Comment by mauben45** [comment]
Thank you for your reply. I also suspected the Bell flight model was the
problem since MSFS still does not support helicopters.
Anyway, thank you for a great little program.

Maurice
