### ISSUE TITLE
TBM-930 Replay...”Don’t Sink!, Don’t Sink!”

### ISSUE THREAD

**Issue by SoCalDude** [nguyenquyhy/Flight-Recorder#83]
I’m using v0.15 with the TBM-930 and am constantly getting the “Don’t sink!, Don’t sink!” warning during playback.  Am I doing something wrong?

**Comment by SoCalDude** [comment]
Just a follow-up on this issue. Is this a true bug with Flight Recorder or with MSFS, or is it not a bug at all?

**Comment by nguyenquyhy** [comment]
I don't know the exact logic when that warning is triggered, so I can't give you a full explanation, but the general idea is that Flight Recorder doesn't record and replay all the states of the aircraft, so some switches will still be at the state when it is on the ground, which most likely will confuse internal system.

I don't consider it a bug though. If you are watching in external view, there is a setting in MSFS to turn off warning sound in this view. Otherwise, you'll have to manually reset what is not replayed.

**Comment by SoCalDude** [comment]
Thank you for the explanation, @nguyenquyhy.
