### ISSUE TITLE
Spoilers not active during Landing replay 

### ISSUE THREAD

**Issue by DRAVMAN91** [nguyenquyhy/Flight-Recorder#99]
Hi ! do you know why Spoilers are not active during landing replay ? Thank you and by the way congrats for this awesome and friendly user tool ! A must to have !

**Comment by nguyenquyhy** [comment]
Which aircraft are you testing this with?

**Comment by DRAVMAN91** [comment]
A320 Neo FBW

**Comment by nguyenquyhy** [comment]
Ah FBW aircraft ignores some data send to the sim from Flight Recorder via SimConnect in order to implememt custom systems & bindings. This will happen to both throttle and spoiler, and might start (or maybe already) to happen to gear handle once the custom hydraulic is implemented. Not much I can do from the tool if the data is ignored by the aircraft 😞.

**Comment by DRAVMAN91** [comment]
Okay Thank you so much for your clear reply. This is much appreciated. anyway, you have craeted a very good and powerful tool. Congrats !
